travis:
  secure:
    BINSTAR_TOKEN: TaSlRiyJudkdcFZwDM10FZod0EoMql7m90P+AoUKUjDI957BD13v6PpLuYUTDNtd8SUcaScVhymtK/qmoy3/RY6vZE1SDyuJgi8Tzj46ztLjb+aR95fUcX2Msojtc4UVsaanMQlikp4IuqDzT12crBbinbStAkVYjT2NkX5g3kER79rPkiMKTjfpQT7yM5HZ9WKLawgRAA0smHokMYmR+h5vIEdZ3UI4CshvMxmr8qsroOsiUnODE3RGAkq99owmqWUoTpRcwr8HuXOuZ89mkol0vSw2W+/ebDYGI3s/P1Wgzi5w4dk2Ku6M/oRaiFIiXzn2mea8dmx5KfirHRKcvY6Uf3cCl87CUVVq8XL2NiLm690RBCNx0NTJXbEX4RwS22sBKcDGVvElXNfT37DPE9KjKfqN6zkjuQ+W4Pok3dyWR3TWQASMBAU/qw89eN1U3uITMqOPRK833BnMpwLddbQsyJqLlgPkeW48+zVcQDFtUJWoPeuYqjATr5KElBoRt7GN/BNqCuuknjX8JgB65YciYpr95NnmNlELUzwSyxtwGodOhjf/Qvm4PBzYxtqCTn10wIhWXm2+bOyUx3GolkCOtl8yMBsIR+jQ6cV1+eyCQluKnnM0GmmyGePS+eb0j5zTnh7euJpN7I6/PxTNnFyOd5OZWmrOSwRU+tRekJU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
